var annotated_dup =
[
    [ "AvatarController", "class_avatar_controller.html", "class_avatar_controller" ],
    [ "AvatarControllerClassic", "class_avatar_controller_classic.html", "class_avatar_controller_classic" ],
    [ "BoneOrientationsConstraint", "class_bone_orientations_constraint.html", "class_bone_orientations_constraint" ],
    [ "BoneOrientationsFilter", "class_bone_orientations_filter.html", "class_bone_orientations_filter" ],
    [ "ClippedLegsFilter", "class_clipped_legs_filter.html", "class_clipped_legs_filter" ],
    [ "CubemanController", "class_cubeman_controller.html", "class_cubeman_controller" ],
    [ "DepthImageViewer", "class_depth_image_viewer.html", null ],
    [ "EggMover", "class_egg_mover.html", null ],
    [ "EggSpawner", "class_egg_spawner.html", "class_egg_spawner" ],
    [ "FollowUserRotation", "class_follow_user_rotation.html", null ],
    [ "GestureListener", "class_gesture_listener.html", "class_gesture_listener" ],
    [ "GetJointPositionDemo", "class_get_joint_position_demo.html", "class_get_joint_position_demo" ],
    [ "JointPositionsFilter", "class_joint_positions_filter.html", "class_joint_positions_filter" ],
    [ "KinectGestures", "class_kinect_gestures.html", "class_kinect_gestures" ],
    [ "KinectHelper", "class_kinect_helper.html", null ],
    [ "KinectManager", "class_kinect_manager.html", "class_kinect_manager" ],
    [ "KinectOverlayer", "class_kinect_overlayer.html", "class_kinect_overlayer" ],
    [ "KinectWrapper", "class_kinect_wrapper.html", "class_kinect_wrapper" ],
    [ "LoadMainLevel", "class_load_main_level.html", null ],
    [ "MouseControl", "class_mouse_control.html", "class_mouse_control" ],
    [ "ObjectRandomLocation", "class_object_random_location.html", null ],
    [ "PresentationScript", "class_presentation_script.html", "class_presentation_script" ],
    [ "SelfIntersectionConstraint", "class_self_intersection_constraint.html", "class_self_intersection_constraint" ],
    [ "SetSceneAvatars", "class_set_scene_avatars.html", null ],
    [ "SimpleGestureListener", "class_simple_gesture_listener.html", "class_simple_gesture_listener" ],
    [ "TimedLerp", "class_timed_lerp.html", "class_timed_lerp" ],
    [ "TrackingStateFilter", "class_tracking_state_filter.html", "class_tracking_state_filter" ]
];